### ISSUE TITLE
Visualization app improvements

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/aframe#177]
- [ ] Add training/validation loss curves to summary page. Eventually include second y-axis for validation metrics mentioned in #41 
- [ ] Event inspector for spectral representation of event, e.g. spectrogram, Q-scan, etc.
- [ ] Some sort of saliency map for each IFO, either gradient wrt time, or gradient wrt freq for each ifo, or gradient wrt to stft (maybe more than one of these)
- [ ] Use actual whitening layer from network for visualization in event inspector
- [ ] Glitch plot legend isn't showing up when using `legend_group` instead of `legend_field` as the argument to `Figure.circle`. The issue with using legend_field as noted [here](https://docs.bokeh.org/en/latest/docs/user_guide/annotations.html#hiding-legend-items) is that Bokeh treats all the legend items as a single item, so you can't click to hide them individually - they're either all on or all off.
- [ ] Toggle at top level for turning vetoes on/off in background distributions

@EthanMarx chime in with any thoughts about exploring performance as a function of event parameters

**Comment by EthanMarx** [comment]
Few more ideas:
- [ ] Existing detection statistic vs SNR scatter plot should have toggle to change SNR to chirp mass, m1, m2 etc.
- [ ] Ability to specify a `t0` and `tf`. All plots will then be recreated only considering events in this time window. 
- [ ] Some visualization that allows us to see our performance on events as a function of time. ( not exactly sure best plot for this at the moment)
