### ISSUE TITLE
Parallelize signal generation

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/aframe#267]
As we scale up our datasets, parallelizing signal generation would speed up data generation, and could also prevent memory issues

**Comment by topefolorunso** [comment]
Hi @wbenoit26.
Could you please tell me more about the signal and data generation? I would love to work on this issue.

**Comment by wbenoit26** [comment]
Hi @topefolorunso

At the moment, we're limiting ourselves to contributions from scientists within IGWN. You can keep an eye on our [contributing guidelines](https://github.com/ML4GW/BBHNet/blob/main/CONTRIBUTING.md) and check if that changes in the future.

**Comment by topefolorunso** [comment]
Okay, thank you.

**Comment by EthanMarx** [comment]
Resolved by condorized waveform generation  n #94
