### ISSUE TITLE
accounting group

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/aframe#303]
Given we are beginning to run our own analyses with condor, we should determine which `accounting_group` we should log
our analyses under. For now, I have chosen `ligo.dev.o4.cbc.explore.test` which is an umbrella for CBC exploratory analyses.
@mcoughlin do you know how we can get such a tag, or if there is already a tag that is well suited for us?

**Comment by mcoughlin** [comment]
@EthanMarx tags come with approval of CBC chairs. And you need to also come with a request on the CPU hours. Once you have that in hand, I am happy to help construct the email.
