### ISSUE TITLE
Bump python version in `parallelize` library

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/aframe#314]
Looks like the `cancel_futures` argument that we use [here](https://github.com/ML4GW/BBHNet/blob/adad78b428f53df21b2a773e6056074e8b260a89/libs/parallelize/bbhnet/parallelize.py#L70) was added in python 3.9, so we should enforce that it's being used.

**Comment by alecgunny** [comment]
This is definitely the right thing to do, but given that after #275 I believe we're going to let Condor handle all our parallelization, and have individual scripts be reasonable serial, I think the better move here will be to just delete the `parallelize` library altogether

**Comment by wbenoit26** [comment]
Good point, agreed.
