### ISSUE TITLE
Standardizing nomenclature

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/aframe#348]
As our code begins to get more and more public eyes on it, we should go through with a fine-toothed comb and standardize a few things that our pre-commit hooks can't check for:
- `n_` vs. `num_`
- `<x>dir` vs. `<x>_dir` vs `<x>_directory`
- Main project executables should live in `main.py` and be called `main`. For those with condorizd equivalents, the thing that gets executed in each condor job should be `main`.
    - Open to other conventions, but they should all be the same
- What else?

**Comment by EthanMarx** [comment]
One big one is signals vs waveforms vs responses

**Comment by EthanMarx** [comment]
Another is `integration_window_size`  vs `integration_size` (former used in infer project, latter in validation)

**Comment by wbenoit26** [comment]
Not sure how much use this will actually be, but I've made a [spreadsheet](https://docs.google.com/spreadsheets/d/1c18oyMVVKFP9MGB_4jGnMmLQ6YMJolgfl9_P1xajGK8/edit?usp=sharing) with all the current variable names.

**Comment by EthanMarx** [comment]
Very cool. Can i ask how you did that

**Comment by wbenoit26** [comment]
I ran `grep -rn --include="*.py" " = " . > var_names.txt` from the top-level `aframe` directory, and then did some post-processing: removed anything from `ml4gw` and `hermes`, stripped off brackets, removed duplicate variables names from the same file, and got rid of anything that obviously didn't belong (like `def func(var ` or any comments with an =). 

There's definitely still some messiness remaining, though, and as I type this, I realize that my initial `grep` missed some cases. But this should be most of them.

**Comment by wbenoit26** [comment]
Also, we reference DeepClean in a couple of comments from copying and pasting

**Comment by wbenoit26** [comment]
For the future, we could rename `LigoResponseSet` to `IfoResponseSet`
