### ISSUE TITLE
Investigate SV dip for production curves/apply vetoes

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/aframe#440]
As it stands, the two re-seeded production training runs have noticeable dips in SV at the lowest FARs, indicating possibly anomalously loud background events.

1. Is this actually the case? Do their foreground distributions match those from earlier runs?
2. Are these events nearly the same for both models?
3. What happens when we apply vetoes?

**Comment by alecgunny** [comment]
@EthanMarx I can tackle (1) if you can tackle (2) and (3)

**Comment by EthanMarx** [comment]
Sounds good!

**Comment by EthanMarx** [comment]
It was discovered that this dip was due to a known event contaminating the background in a timeslide.
